### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by amouly** [andreatondo/foscam-snapshot-nodejs#1]
Thanks for sharing this, it's awesome. Any idea to continue improving this, and support any other functions from the Foscam API? Do you have any file reference of the API?

**Comment by andreatondo** [comment]
Adrián, thanks for starring it.
I don't have any clear plans about extending this project right now, but suggestions are always welcome.
Foscam offers quite a large number of CGI methods, this appears to me to be the most recent official documentation: http://foscam.devcenter.me
